### ISSUE TITLE
Semrush Losing Connection

### ISSUE THREAD

**Issue by wjamieson** [umbraco/Umbraco.Cms.Integrations#177]
Umbraco Version: 8.18.12
Umbraco.Cms.Integrations.SEO.Semrush Version: 1.2.2

Config variables:
Umbraco.Cms.Integrations.SEO.Semrush.BaseUrl: "https://oauth.semrush.com/"
Umbraco.Cms.Integrations.SEO.Semrush.UseUmbracoAuthorization: "true"

We have been successfully using the Semrush plugin on two client sites however both seem to be encountering a problem where they routinely lose connection to Semrush and stop working. The "Status" button still reports as connected, but the plugin stops working until the client runs through the authentication process again. We have been monitoring this and it seems to occur over weekends, possibly due to inactivity.

Have you encountered this problem before and is there a way to extend the length of time the authorisation remains valid?

**Comment by acoumb** [comment]
Hi @wjamieson ,

I have released version [1.2.4](https://www.nuget.org/packages/Umbraco.Cms.Integrations.SEO.Semrush/1.2.4) with a fix for this. 
Due to the fact that the access token was expired and couldn't be refreshed using the access token, the UI was not updated properly.

Thank you for bring this to our attention,
Adrian
