### ISSUE TITLE
Cannot change credentials or use app user to authenticate to CRM

### ISSUE THREAD

**Issue by mkalinov** [umbraco/Umbraco.Cms.Integrations#80]
Hi Umbraco team,

We trying to set up integration between Umbraco portal and Dynamics 365 Marketing as per [this article](https://umbraco.com/blog/integrating-umbraco-cms-with-microsoft-dynamics-365-marketing-forms/).

We updated the config, deployed to umbraco, 
Inserted personal user credentials. 
Once we revoked user credentials , the portal did not allow us to add new credentials or change user. 
Looks like it uses personal user credentials stored in db.

This may create an issue if user lives organization, changes password etc.
Is there a way to remove/change user?

Another thing.

The best practice in crm integration is to utilize app user (web app in Azure synced to crm as non-interactive user).
In this situation client_id/client_secret shall be utilized on authentication.
Is it possible?

**Comment by acoumb** [comment]
Hi @mkalinov ,

We only store the access token retrieved by Microsoft's API and the name of the user we retrieve based on the access token. When you choose to `Revoke` from the configuration section of the data type, the record is removed from the database.

If you are referring to the fact that this prompt
![2023-01-31_13-13-40](https://user-images.githubusercontent.com/95346674/215747792-0ff72719-b581-42de-84e0-562bb939084e.png)
does not show again when you try to connect, it's because the browser has an authorization cookie stored from the moment you've signed up, and I think Microsoft picks that. Clearing the browser's cookies will do the trick in this scenario.

Regarding your other thing, we are using an Azure App registered under Umbraco for managing authentication, but we are considering adding an extension to the package allowing you to use your own for managing authorization.

Hope my explanations make sense, let me know if you have other questions.

Thank you,
Adrian

**Comment by mkalinov** [comment]
Thanks @acoumb,

It's strange because any kind of password/credential cache is off on the browser.
I will double check that.

Web App approach would be the best, and as per MS - the best practice.

**Comment by acoumb** [comment]
Hi @mkalinov ,

Could you share with me a link about this? 

I am taking into consideration having the authorization process accessible to the user on their own implementation.

Thank you.

**Comment by mkalinov** [comment]
https://learn.microsoft.com/en-us/power-platform/admin/manage-application-users 

https://powerapps.microsoft.com/en-us/blog/administer-application-users-security-roles-teams-and-users-in-the-power-platform-admin-center/

This post describes the concept very well: 
https://www.inogic.com/blog/2018/10/obtain-organizationservice-using-application-user-in-dynamics-365/

**Comment by acoumb** [comment]
Thank you for providing me this information, I will take them into consideration while we prepare a new major release for the package.

In the meantime, I will close this, please reach out if you have other questions or encounter issues.

Thank you
